### ISSUE TITLE
Scala 2.12 support?

### ISSUE THREAD

**Issue by dalegaspi** [Tradeshift/ts-reaktive#64]
is scala 2.12 support on the horizon?  thank you!

**Comment by jypma** [comment]
We're not actively working on Scala 2.12 support. However, given that the amount of actual Scala code in the project is fairly minimal, it may cross-compile to 2.12 just fine. Have you tried just bumping the version and compiling it? I'd be happy to work together to add support for it.

**Comment by jypma** [comment]
Added Scala 2.12 support in version [0.0.29](https://github.com/Tradeshift/ts-reaktive/releases/tag/v0.0.29).
